// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdfvxypfswdjxdgzxtmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZnZ4eXBmc3dkanhkZ3p4dG1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTM3MTgsImV4cCI6MjA1OTU4OTcxOH0.RCBNth9USx2zgi4OqflBh0_J_qDwsHEVsG1W-eoDmms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);